name: L2C-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macOS-latest]
        python-version: ["3.9"]
    name: Python ${{ matrix.python-version }} example

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda config --add channels conda-forge
        conda config --set always_yes yes
        conda install compilers python=${{ matrix.python-version }}
        conda env update --file environment.yml --name base
    - run: |
        cd C
        meson setup build
        cd build
        meson compile
        meson test

