name: L2C-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: ["3.8", "3.9", "3.10"]
    name: Python ${{ matrix.python-version }} example

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda config --add channels conda-forge
        conda config --set always_yes yes
        conda create -n l2c python=${{ matrix.python-version }}
        conda env update --file environment.yml --name l2c
    - run: |
        cd src
        source activate l2c
        pip install pytest
        meson setup build --prefix=$PWD/build-install
        export PYTHONPATH=$PYTHONPATH:$PWD/build-install/lib/python${{ matrix.python-version }}/site-packages
        echo $CXXFLAGS -I$CONDA_PREFIX/include
        export CXXFLAGS=$CXXFLAGS' '-I$CONDA_PREFIX/include
        echo $CXXFLAGS
        export CFLAGS=$CFLAGS' '-I$CONDA_PREFIX/include
        export $CFLAGS
        ls $CONDA_PREFIX/include
        meson install -C build
        meson test -v -C build
