name: L2C-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    name: Python ${{ matrix.python-version }} example

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda config --add channels conda-forge
        conda config --set always_yes yes
        conda create -n l2c python=${{ matrix.python-version }}
        conda env update --file environment.yml --name l2c
    - run: |
        cd src
        source activate l2c
        meson setup build --prefix=$PWD/build-install --includedir=$CONDA_PREFIX/include --libdir=$CONDA_PREFIX/lib
        export PYTHONPATH=$PYTHONPATH:$PWD/build-install/lib/python${{ matrix.python-version }}/site-packages
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/build-install/lib
        export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$PWD/build-install/lib
        meson configure -Dc_args=-DTEST build
        meson install -C build
        meson test -v -C build
